name: ci

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Update packages list
      run: sudo apt update
      
    - name: Install packages
      run: sudo apt install python3-pip -y
      
    - name: Install cpplint
      run: pip3 install cpplint

    - name: Run cpplint
      working-directory: ${{runner.workspace}}/${{github.event.repository.name}}
      shell: bash
      run: $HOME/.local/bin/cpplint --filter=-legal/copyright,-build/include_subdir,-build/c++11,-build/include_order $(find -name "*.h" -o -name "*.cpp")

  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Update packages list
      run: sudo apt update
      
    - name: Install packages
      run: sudo apt install build-essential libssl-dev curl -y
      
    - name: Install Curl
      run: sudo apt-get install libcurl4-openssl-dev

    - name: Install CMake
      run: sudo snap install cmake --classic

    - name: Create Makefile
      working-directory: ${{runner.workspace}}/${{github.event.repository.name}}
      run: cmake -DCMAKE_BUILD_TYPE=Release ./CMakeLists.txt

    - name: Build
      working-directory: ${{runner.workspace}}/${{github.event.repository.name}}
      run: cmake --build . -j2
